ProjectFINAL/Controllers/HomeController.cs
using Newtonsoft.Json;
using Project.Business;
using Project.Entity;
using ProjectFINAL.ApiModel;
using ProjectFINAL.ViewModels;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ProjectFINAL.Controllers
{
    public class HomeController : BaseController
    {
        private UserService userService;
        private WateringHistoryService wateringHistoryService;
        private HumidityHistoryService humidityHistoryService;
        private PlannedWateringService plannedWateringService;
        private PlantService plantService;
        public HomeController()
        {
            userService = new UserService();
            wateringHistoryService = new WateringHistoryService();
            humidityHistoryService = new HumidityHistoryService();
            plannedWateringService = new PlannedWateringService();
            plantService = new PlantService();
        }
        private async Task<WeatherResponseModel> SetWeatherCondition()
        {
            var url = "http://api.weatherapi.com";
            var client = new RestClient(url);
            var request = new RestRequest("/v1/current.json", Method.Get);
            request.AddQueryParameter("key", "bd711085065843fe8a883757220106");
            request.AddQueryParameter("q", "istanbul");
            request.AddQueryParameter("lang", "tr");
            var result = await client.ExecuteAsync(request);
            var model = new WeatherResponseModel();
            if (result.StatusCode == System.Net.HttpStatusCode.OK)
                model = JsonConvert.DeserializeObject<WeatherResponseModel>(result.Content);
            return model;
        }
        public async Task<ActionResult> Index()
        {
            

            var allPlants = plantService.GetPlantListById((int)Session["Id"]);
            var plantIdList = new List<int>();
            foreach(var item in allPlants.Data)
            {
                plantIdList.Add(item.Id);
            }
            var totalTodayWateringPlanCount = wateringHistoryService.FindBy(x => x.CreatedTime.Year == DateTime.Now.Year
            && x.CreatedTime.Month == DateTime.Now.Month && x.CreatedTime.Day == DateTime.Now.Day && plantIdList.Contains(x.PlantId)).Data;
            ViewBag.TodayWatered = totalTodayWateringPlanCount.Count();


            ViewBag.TotalPlantCount = allPlants.Data.Count;

            var totalWateringCount = 0;
            foreach (var item in allPlants.Data)
            {
                totalWateringCount += wateringHistoryService.FindBy(x => x.PlantId == item.Id).Data.Count();
            }
            ViewBag.TotalAutomaticWatering = totalWateringCount;


            var viewModel = new IndexViewModel
            {
                PlantInformation = new List<DTO.PlantDTO>()
            };

            var usersPlants = new PlantService().GetPlantListById((int)Session["Id"]);
            foreach (var item in usersPlants.Data)
            {
                var lastWatered = wateringHistoryService.GetLastWateringTime(item.Id);
                viewModel.PlantInformation.Add(new DTO.PlantDTO
                {
                    Plant = item,
                    LastWateredTime = lastWatered.Data ?? new DateTime?(),
                    CurrentHumidityRate = humidityHistoryService.GetCurrentHumidityRateByPlantId(item.Id).Data != null ? (decimal)humidityHistoryService.GetCurrentHumidityRateByPlantId(item.Id).Data.HumidityRate : 0,
                    WateringType = plannedWateringService.GetByPlantId(item.Id).Data.WateringType ?? WateringType.Not_Set
                });
            }

            viewModel.Weather = await SetWeatherCondition();

            return View(viewModel);
        }

        public ActionResult MyPlants()
        {
            return View();
        }
    }
}

ProjectFINAL/Controllers/PlantController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Project.Business;
using Project.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectFINAL.Controllers
{
    public class PlantController : BaseController
    {
        // GET: Plant
        private PlantService plantService;
        private HumidityHistoryService humidityHistoryService;
        private PlannedWateringService plannedWateringService;
        public PlantController()
        {
            plantService = new PlantService();
            humidityHistoryService = new HumidityHistoryService();
            plannedWateringService = new PlannedWateringService();
        }

        public ActionResult AddPlant()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddPlant(Plant plant)
        {
            var result = plantService.Add(new Plant
            {
                Name = plant.Name,
                UserId = plant.UserId
            });
            if (result.HasError)
            {
                ViewBag.ErrMsg = result.ResultMessage;
                return View();
            }
            TempData["Success"] = "Bitki başarıyla eklendi";
            return RedirectToAction("Index", "Home");
        }
        public ActionResult Status(int id)
        {
            var result = plantService.GetById(id);
            ViewBag.LastWateredTime = new WateringHistoryService().GetLastWateringTime(id);
            var last24hour = DateTime.Now.AddHours(-24);
            ViewBag.WateringTimeInToday = new WateringHistoryService().FindBy(x => x.CreatedTime > last24hour && x.CreatedTime < DateTime.Now && x.PlantId == id);
            return View(result.Data);
        }
        public ActionResult WateringOptions(int id)
        {
            var plannedWatering = plannedWateringService.GetByPlantId(id);

            if (plannedWatering.Data == null)
            {
                var result = plannedWateringService.Add(new Project.Entity.PlannedWaterings
                {
                    PlantId = id
                });
                if (!result.HasError)
                    plannedWatering = plannedWateringService.GetByPlantId(id);
            }
            return View(plannedWatering.Data);

        }
        [HttpPost]
        public ActionResult WateringOptions(PlannedWaterings model)
        {
            var result = plannedWateringService.Update(model);
            if (!result.HasError)
            {
                TempData["Success"] = "Başarıyla kaydedildi";
            }
            else
            {
                TempData["ErrMsg"] = result.ResultMessage;
            }
            return RedirectToAction("Index", "Home");

        }
    }
}

ProjectFINAL/Views/Home/Index.cshtml
@using ProjectFINAL.Helper;
@using Project.Entity;
@model ProjectFINAL.ViewModels.IndexViewModel
@{
    ViewBag.Title = "Home Page";
}


<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6 mt-5">
                <div class="card">
                    <div class="card-header border-0">
                        <div class="d-flex justify-content-between">
                            <h3 class="card-title">Hava Durumu</h3>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="info-box">
                                    <span class="info-box-icon bg-info"><i class="fa-solid fa-temperature-low"></i></span>

                                    <div class="info-box-content">
                                        <span class="info-box-text">@Model.Weather.current.condition.text</span>
                                        <span class="info-box-number">@Model.Weather.current.temp_c °C</span>

                                    </div>
                                    <div class="icon">
                                        <span class="info-box-content float-right"><img class="img-fluid" width="50" src="@Model.Weather.current.condition.icon" /></span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="info-box">
                                    <span class="info-box-icon bg-info"><i class="fa-solid fa-droplet"></i></span>

                                    <div class="info-box-content">
                                        <span class="info-box-text">Nem Oranı</span>
                                        <span class="info-box-number">@Model.Weather.current.humidity%</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="info-box">
                                    <span class="info-box-icon bg-info"><i class="fa-solid fa-face-grin-beam-sweat"></i></span>

                                    <div class="info-box-content">
                                        <span class="info-box-text">Hissedilen Sıcaklık</span>
                                        <span class="info-box-number">@Model.Weather.current.feelslike_c °C</span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="info-box">
                                    <span class="info-box-icon bg-info"><i class="fa-solid fa-wind"></i></span>

                                    <div class="info-box-content">
                                        <span class="info-box-text">Rüzgar Hızı</span>
                                        <span class="info-box-number">@Model.Weather.current.wind_kph Km/saat</span>
                                    </div>
                                </div>
                            </div>
                        </div>



                    </div>
                </div>
                <!-- /.card -->

                <div class="card">
                    <div class="card-header border-0">
                        <h3 class="card-title">Bitkiler</h3>
                        <div class="card-tools">
                            <a href="#" class="btn btn-tool btn-sm">
                                <i class="fas fa-bars"></i>
                            </a>
                        </div>
                    </div>
                    <div class="card-body table-responsive p-0">
                        <table class="table table-striped table-valign-middle">
                            <thead>
                                <tr>
                                    <th>Bitki</th>
                                    <th>Son Sulanma</th>
                                    <th>Anlık Nem</th>
                                    <th>Sulama Ayarı</th>
                                    <th>Detay</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{ 
                                    var list = Helper.GetEnumValuesAndDescriptions<WateringType>();
                                    
                                }
                                @foreach (var item in Model.PlantInformation)
                                {
                                <tr>
                                    <td>

                                        @item.Plant.Name
                                    </td>
                                    <td>@(item.LastWateredTime.ToString() ?? "Sulanmadı")</td>
                                    <td>
                                        @item.CurrentHumidityRate
                                    </td>
                                    <td>
                                        @list.Find(x => x.Value == (int)item.WateringType).Key
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Status","Plant", new {id=item.Plant.Id })" class="text-muted">
                                           <i class="fas fa-search"></i>
                                        </a>
                                    </td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col-md-6 -->
            <div class="col-lg-6 mt-5">
                <div class="small-box bg-warning">
                    <div class="inner">
                        <h3>@ViewBag.TotalPlantCount</h3>

                        <p>Toplam Bitki Sayısı</p>
                    </div>
                    <div class="icon">
                        <i class="fa-solid fa-seedling"></i>
                    </div>
                </div>
                <div class="small-box bg-warning">
                    <div class="inner">
                        <h3>@ViewBag.TotalAutomaticWatering</h3>

                        <p>Toplam Otomatik Sulama Sayısı</p>
                    </div>
                    <div class="icon">
                        <i class="fa-solid fa-faucet-drip"></i>
                    </div>
                </div>
                <!-- /.card -->

                <div class="card">
                    <div class="card-header border-0">
                        <h3 class="card-title">Günlük Veriler</h3>
                        <div class="card-tools">
                            <a href="#" class="btn btn-sm btn-tool">
                                <i class="fas fa-bars"></i>
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="info-box">
                            <span class="info-box-icon bg-success"><i class="far fa-flag"></i></span>

                            <div class="info-box-content">
                                <span class="info-box-text">Bugün Sulanan</span>
                                <span class="info-box-number">@ViewBag.TodayWatered</span>
                            </div>
                            <!-- /.info-box-content -->
                        </div>
                        <!-- /.d-flex -->
                        <!-- /.d-flex -->
                    </div>
                </div>
            </div>
            <!-- /.col-md-6 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>